using Colegio.Domain.Entities;
using Colegio.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace Colegio.Api.Endpoints;

public static class TimetableFrameworkEndpoints
{
    public static void MapTimetableFrameworkEndpoints(this WebApplication app)
    {
        var group = app.MapGroup("/api/frameworks").WithTags("Timetable Frameworks");

        group.MapGet("/", GetAllFrameworks);
        group.MapGet("/{id}", GetFrameworkById);
        group.MapPost("/", CreateFramework);
        group.MapPut("/{id}", UpdateFramework);
        group.MapDelete("/{id}", DeleteFramework);
        group.MapPost("/{id}/generate-slots", GenerateTimeSlots);
    }

    private static async Task<IResult> GetAllFrameworks(ColegioDbContext db)
    {
        var frameworks = await db.TimetableFrameworks
            .Include(f => f.Breaks)
            .AsNoTracking()
            .ToListAsync();
        return Results.Ok(frameworks);
    }

    private static async Task<IResult> GetFrameworkById(ColegioDbContext db, Guid id)
    {
        var framework = await db.TimetableFrameworks
            .Include(f => f.Breaks)
            .FirstOrDefaultAsync(f => f.Id == id);
        
        return framework is null ? Results.NotFound() : Results.Ok(framework);
    }

    private static async Task<IResult> CreateFramework(ColegioDbContext db, TimetableFramework framework)
    {
        framework.Id = Guid.NewGuid();
        db.TimetableFrameworks.Add(framework);
        await db.SaveChangesAsync();
        return Results.Created($"/api/frameworks/{framework.Id}", framework);
    }

    private static async Task<IResult> UpdateFramework(ColegioDbContext db, Guid id, TimetableFramework updated)
    {
        var framework = await db.TimetableFrameworks
            .Include(f => f.Breaks)
            .FirstOrDefaultAsync(f => f.Id == id);
            
        if (framework is null) return Results.NotFound();

        framework.Name = updated.Name;
        framework.SessionType = updated.SessionType;
        framework.HasAfternoon = updated.HasAfternoon;
        framework.MorningStart = updated.MorningStart;
        framework.MorningEnd = updated.MorningEnd;
        framework.AfternoonStart = updated.AfternoonStart;
        framework.AfternoonEnd = updated.AfternoonEnd;
        framework.SessionDurationMinutes = updated.SessionDurationMinutes;

        // Update Breaks
        db.BreakDefinitions.RemoveRange(framework.Breaks);
        foreach (var b in updated.Breaks)
        {
            b.Id = Guid.NewGuid();
            b.TimetableFrameworkId = id;
            db.BreakDefinitions.Add(b);
        }

        await db.SaveChangesAsync();
        return Results.Ok(framework);
    }

    private static async Task<IResult> DeleteFramework(ColegioDbContext db, Guid id)
    {
        var framework = await db.TimetableFrameworks.FindAsync(id);
        if (framework is null) return Results.NotFound();

        db.TimetableFrameworks.Remove(framework);
        await db.SaveChangesAsync();
        return Results.NoContent();
    }

    private static async Task<IResult> GenerateTimeSlots(ColegioDbContext db, Guid id)
    {
        var framework = await db.TimetableFrameworks
            .Include(f => f.Breaks)
            .FirstOrDefaultAsync(f => f.Id == id);
            
        if (framework is null) return Results.NotFound();

        // Remove old slots generated by this framework
        var oldSlots = await db.TimeSlots
            .Where(ts => ts.TimetableFrameworkId == id)
            .ToListAsync();
        db.TimeSlots.RemoveRange(oldSlots);

        var newSlots = new List<TimeSlot>();
        var days = new[] { Colegio.Domain.Entities.DayOfWeek.Monday, Colegio.Domain.Entities.DayOfWeek.Tuesday, Colegio.Domain.Entities.DayOfWeek.Wednesday, Colegio.Domain.Entities.DayOfWeek.Thursday, Colegio.Domain.Entities.DayOfWeek.Friday };

        foreach (var day in days)
        {
            // Morning
            GenerateSlotsInRange(framework, day, framework.MorningStart, framework.MorningEnd, newSlots);

            // Afternoon
            if (framework.HasAfternoon && framework.AfternoonStart.HasValue && framework.AfternoonEnd.HasValue)
            {
                GenerateSlotsInRange(framework, day, framework.AfternoonStart.Value, framework.AfternoonEnd.Value, newSlots);
            }
        }

        db.TimeSlots.AddRange(newSlots);
        await db.SaveChangesAsync();

        return Results.Ok(new { Count = newSlots.Count });
    }

    private static void GenerateSlotsInRange(TimetableFramework framework, Colegio.Domain.Entities.DayOfWeek day, TimeSpan start, TimeSpan end, List<TimeSlot> slots)
    {
        var current = start;
        var duration = TimeSpan.FromMinutes(framework.SessionDurationMinutes);

        while (current + duration <= end)
        {
            // Check for breaks that start at 'current' or overlap with the potential session
            var @break = framework.Breaks.FirstOrDefault(b => b.StartTime == current);
            
            if (@break != null)
            {
                slots.Add(new TimeSlot
                {
                    Id = Guid.NewGuid(),
                    TimetableFrameworkId = framework.Id,
                    SessionType = framework.SessionType,
                    DayOfWeek = day,
                    StartTime = @break.StartTime,
                    EndTime = @break.EndTime,
                    IsBreak = true,
                    Label = @break.Label
                });
                current = @break.EndTime;
            }
            else
            {
                // Create a normal session
                slots.Add(new TimeSlot
                {
                    Id = Guid.NewGuid(),
                    TimetableFrameworkId = framework.Id,
                    SessionType = framework.SessionType,
                    DayOfWeek = day,
                    StartTime = current,
                    EndTime = current + duration,
                    IsBreak = false,
                    Label = "" // Standard session
                });
                current += duration;
            }
        }
    }
}
